"""Added is_admin column to User model

Revision ID: 1368f675528e
Revises: 
Create Date: 2025-03-31 10:50:32.200389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1368f675528e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_delays')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('flight_delays',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flight_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('origin', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('destination', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('scheduled_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delay_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='flight_delays_pkey')
    )
    # ### end Alembic commands ###
